ALTER TABLE games ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE sagas ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE experiences ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE online_playtimes ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT now();
